// Generated by gencpp from file human_robot_comm/floatlist.msg
// DO NOT EDIT!


#ifndef HUMAN_ROBOT_COMM_MESSAGE_FLOATLIST_H
#define HUMAN_ROBOT_COMM_MESSAGE_FLOATLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace human_robot_comm
{
template <class ContainerAllocator>
struct floatlist_
{
  typedef floatlist_<ContainerAllocator> Type;

  floatlist_()
    : data()  {
    }
  floatlist_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::human_robot_comm::floatlist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::human_robot_comm::floatlist_<ContainerAllocator> const> ConstPtr;

}; // struct floatlist_

typedef ::human_robot_comm::floatlist_<std::allocator<void> > floatlist;

typedef boost::shared_ptr< ::human_robot_comm::floatlist > floatlistPtr;
typedef boost::shared_ptr< ::human_robot_comm::floatlist const> floatlistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::human_robot_comm::floatlist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::human_robot_comm::floatlist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace human_robot_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'human_robot_comm': ['/home/albertwu/me212project/catkin_ws/src/human_robot_comm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::human_robot_comm::floatlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::human_robot_comm::floatlist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_robot_comm::floatlist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::human_robot_comm::floatlist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_robot_comm::floatlist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::human_robot_comm::floatlist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::human_robot_comm::floatlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "420cd38b6b071cd49f2970c3e2cee511";
  }

  static const char* value(const ::human_robot_comm::floatlist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x420cd38b6b071cd4ULL;
  static const uint64_t static_value2 = 0x9f2970c3e2cee511ULL;
};

template<class ContainerAllocator>
struct DataType< ::human_robot_comm::floatlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "human_robot_comm/floatlist";
  }

  static const char* value(const ::human_robot_comm::floatlist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::human_robot_comm::floatlist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] data\n\
";
  }

  static const char* value(const ::human_robot_comm::floatlist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::human_robot_comm::floatlist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct floatlist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::human_robot_comm::floatlist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::human_robot_comm::floatlist_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HUMAN_ROBOT_COMM_MESSAGE_FLOATLIST_H
